name: Download and Extract GCP Logs

on:
  workflow_dispatch:
    inputs:
      uuid:
        description: 'UUID to filter logs (textPayload)'
        required: true
        type: string
      environment:
        description: 'Environment (stage or prod)'
        required: true
        type: choice
        options:
          - stage
          - prod

jobs:
  download-logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ github.event.inputs.environment == 'prod' && secrets.GCP_SA_KEY_PROD || secrets.GCP_SA_KEY_STAGE }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
  
      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Download logs with user-provided UUID
        run: |
          gcloud logging read \
            "textPayload:\"${{ github.event.inputs.uuid }}\"" \
            --format=json > gcp_logs.json

      # - name: Extract textPayload and save to text file
      #   run: |
      #     cat gcp_logs.json | jq -r '.[].textPayload' > extracted_logs.txt

      - name: Upload logs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: extracted-gcp-logs
          path: gcp_logs.json
      
      - name: Extract textPayload
        run: |
          cat gcp_logs.json | jq -r 'reverse | .[] | .textPayload' input.json > textPayload.txt
          cat textPayload.txt  # To verify output

      - name: Upload text file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: textPayload
          path: textPayload.txt
