name: '[Trigger] Sync & Import Data | Auth0 Tenants | FB Remote Config'
on:
  workflow_dispatch:
    inputs:
      auth0_import_permission:
        description: "Import Permissions to AUTH0"
        required: true
        default: false
        type: boolean
      auth0_import_users:
        description: "Import Users to AUTH0"
        required: true
        default: false
        type: boolean
      auth0_delete_users_before_import:
        description: "Delete Users before AUTH0 Import"
        required: true
        default: false
        type: boolean
      auth0_sync_tenant:
        description: "Sync AUTH0 Tenants"
        required: true
        default: false
        type: boolean
      firebase_sync_rc:
        description: "Sync Firebase Remote Config"
        required: true
        default: false
        type: boolean
      auth0_source_tenant:
        description: 'Auth0 Source Tenant'
        required: true
        type: choice
        options:
          - DEV
          - STAGE
          - PROD
      auth0_dest_tenant:
        description: 'Auth0 Destination Tenant'
        required: true
        type: choice
        options:
          - DEV
          - STAGE
      firebase_source_env:
        description: 'Firebase Source Environment'
        required: true
        type: choice
        options:
          - STAGE
          - PROD
      firebase_dest_env:
        description: 'Firebase Destination Environment'
        required: true
        type: choice
        options:
           - STAGE
           - PROD

jobs:
       
  import_data:
        uses: nabarun-ngo/ngo-nabarun-templates/.github/workflows/Auth0-Import.yml@main
        with:
              branch_name: 'main'
              source: 'google_drive'
              auth0_import_tenant: ''
              input_file: ''
              import_data: ''
              import_user: ''
              delete_old_user: ''
              doppler_project: ''
              doppler_service_token: ${{ secrets.DOPPLER_CONFIG_ }}
              gcp_service_account: ${{ secrets.AUTH0_CREDENTIALS }}
   
