name: 'Manual Trigger : Run Automated Test'
on:
  workflow_dispatch:
    inputs:
     target_env:
       required: true
       description: 'Env'
       type: choice
       options:
         - stage
         - prod
     cucumber_tags:
       description: 'Cucumber Tags'
       required: true
       type: string
       default: '@regression'
     test_cycle_id:
       description: 'Test Cycle'
       required: true
       type: string
       default: 'NAB-TR-2' 
     test_type:
       required: true
       description: 'Test Type'
       type: choice
       options:
         - Regression
         - Smoke

jobs:
   run_automated_test:
    name: Run Automation Test 
    if: github.event.inputs.target_env != 'prod'
    uses: nabarun-ngo/ngo-nabarun-templates/.github/workflows/Run-Tests.yml@main
    with:
        test_env: ${{ github.event.inputs.target_env }}
        test_doppler_project_name: 'nabarun_test'
        test_cycle: ${{ github.event.inputs.test_type == 'Smoke' && vars.SMOKE_TEST_CYCLE_STAGE || vars.REGRESSION_TEST_CYCLE_STAGE }}
        upload_result: true 
        test_cucumber_tags: ${{ github.event.inputs.cucumber_tags}}
        test_type: ${{ github.event.inputs.test_type }}
    secrets:
      test_doppler_service_token: ${{ secrets.DOPPLER_TEST_SERVICE_TOKEN_STAGE }}
      qmetry_api_key: ${{ secrets.QMETRY_APIKEY }}
      
   run_automated_test_prod:
    name: Run Automation Test (PROD)
    if: github.event.inputs.target_env == 'prod'
    uses: nabarun-ngo/ngo-nabarun-templates/.github/workflows/Run-Tests.yml@main
    with:
        test_env: 'prod'
        test_doppler_project_name: 'nabarun_test'
        test_cycle: vars.SMOKE_TEST_CYCLE_PROD
        upload_result: true 
        test_cucumber_tags: '@smokeprod'
        test_type: 'Smoke'
    secrets:
      test_doppler_service_token: ${{ secrets.DOPPLER_TEST_SERVICE_TOKEN }}
      qmetry_api_key: ${{ secrets.QMETRY_APIKEY }}
      
   
